### ISSUE TITLE
Filter w/o variable Parameters not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#354]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Not able to use a predefined Filter criteria w/o variable filter parameters.
Further Info: it seems as if "mandatory parameter missing" happens if you switch between filter w/o variable parameter and one with a variable parameter.
#### Which are the steps to reproduce?
Open material Receipt Candidates Window. Press Filter Selection. Choose "Streckengeschäft". Nothing happens (see error)
### What is the expected or desired behavior?
Shall be filtered w/ the given constant criteria.

![image](https://cloud.githubusercontent.com/assets/13365687/23104233/ef75cd24-f6c9-11e6-92df-37f5d17d1da6.png)

**Comment by damianprzygodzki** [comment]
Fixed from front end side. When i am setting filter without any parameters there is NullPointerException without message from API.

**Comment by teosarca** [comment]
Works. Thanks.

**Comment by teosarca** [comment]
Reopening because i found another issue:
* after u selected & applied that filter everything is OK
* but if u click again of filters button you got an error

![Uploading image.png…]()

**Comment by metas-lc** [comment]
IT
1) Open material Receipt Candidates Window. Press Filter Selection. Choose "Streckengeschäft" => filter applied OK
2) click again of filters button => no error. OK
3) change filter several times => filter was applied each time OK

Discovered an issue: 
* add a filter in  material Receipt Candidates Window (e.g. a product). Apply. 
* press on home button, select Billing Candidates, see filter => filter is like it was in receipt schedules. NOK

**Comment by metas-lc** [comment]
IT
about filter not changing when you change the window
if i go from a window directly to another (without any refresh) i can still see there is a filter (even if it's not applied)
![filter1](https://cloud.githubusercontent.com/assets/16001666/23128264/f25da36e-f786-11e6-9263-27f68a254294.png)

after that, if i press on refresh, the filter is gone
![filter2](https://cloud.githubusercontent.com/assets/16001666/23128279/0682aa24-f787-11e6-88ff-a938c21c9678.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce. It should be fixed by 93df3e9, looks like outdated build.

**Comment by metas-mk** [comment]
@damianprzygodzki Tested. Works now in current build. Thanks.

**Comment by damianprzygodzki** [comment]
issue occurs: 540092 with default filter (product) -> 540196

**Comment by metas-lc** [comment]
IT:
1. Open material Receipt Candidates Window. Press Filter Selection. Choose "Streckengeschäft" => filter applied OK
2. click again of filters button => no error. OK
3. change filter several times => filter was applied each time OK
4. set a filter in receipt candidates (e.g. product), move directly to another window that has the same filter (e.g. invoice candidates) => no filter set OK

**Comment by metas-lc** [comment]
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23354.md
